"""Canonical enums for the device-management bounded context (Milestone 7)."""

# ---------------------------------------------------------------------------
# Device onboarding / lifecycle
# ---------------------------------------------------------------------------
DEVICE_STATES = (
    "DISCOVERED", "QUARANTINED", "IDENTIFIED", "CLAIM_PENDING", "CLAIMED",
    "INVENTORY_MATCHED", "ASSIGNED", "PROVISIONING", "ACTIVE", "REJECTED",
    "DUPLICATE", "SECURITY_HOLD", "OFFLINE", "DECOMMISSIONED",
)
TERMINAL_DEVICE_STATES = {"REJECTED", "DUPLICATE", "DECOMMISSIONED"}

TENANT_RESOLUTION_METHODS = (
    "PREREGISTERED_SERIAL", "OUI_PRODUCT_SERIAL", "TECHNICIAN_INSTALLATION",
    "OSS_ORDER_RESERVATION", "ONBOARDING_TOKEN", "ACS_ENDPOINT",
    "CIRCUIT_SERVICE_MAPPING", "ADMIN_CLAIM",
)
TENANT_RESOLUTION_RESULTS = ("MATCHED", "AMBIGUOUS", "UNKNOWN", "BLOCKED", "CONFLICT")

CAPABILITY_STATES = ("CONFIRMED", "INFERRED", "UNVERIFIED", "UNSUPPORTED", "VENDOR_SPECIFIC", "CHANGED_AFTER_FIRMWARE")

DEVICE_DATA_MODEL_FAMILIES = ("TR098", "TR181", "VENDOR_SPECIFIC", "UNKNOWN")
DEVICE_DATA_MODEL_VERSIONS = ("1.0", "2.0", "2.1", "UNKNOWN")

# ---------------------------------------------------------------------------
# Configuration profiles & jobs
# ---------------------------------------------------------------------------
PROFILE_STATES = ("DRAFT", "REVIEW", "APPROVED", "SCHEDULED", "ACTIVE", "SUPERSEDED", "DISABLED", "ARCHIVED")
PROFILE_ACTIVE_STATES = {"APPROVED", "ACTIVE"}

CONFIGURATION_JOB_STATES = (
    "DRAFT", "VALIDATING", "READY", "QUEUED", "CONNECTION_REQUEST_PENDING",
    "WAITING_FOR_INFORM", "EXECUTING", "DEVICE_ACKNOWLEDGED", "VERIFYING",
    "SUCCEEDED", "FAILED", "TIMED_OUT", "CANCELLED", "ROLLBACK_PENDING",
    "ROLLED_BACK", "MANUAL_INTERVENTION_REQUIRED",
)
TERMINAL_CONFIGURATION_JOB_STATES = {"SUCCEEDED", "FAILED", "TIMED_OUT", "CANCELLED", "ROLLED_BACK"}

CONFIGURATION_STEP_STATES = ("PENDING", "QUEUED", "DISPATCHED", "DEVICE_RESPONSE", "VERIFIED", "FAILED", "TIMED_OUT")

VERIFICATION_STATES = ("PENDING", "VERIFIED", "DRIFT_DETECTED", "FAILED", "UNREADABLE", "NOT_APPLICABLE")

DRIFT_CLASSIFICATIONS = (
    "NONE", "EXPECTED", "USER_CHANGE", "DEVICE_RESET", "FIRMWARE_CHANGE",
    "PROVISIONING_FAILURE", "UNSUPPORTED_PARAMETER", "SECURITY_CRITICAL", "UNKNOWN",
)
DRIFT_POLICIES = (
    "REPORT_ONLY", "AUTO_REPAIR", "REPAIR_IN_WINDOW", "REQUIRE_APPROVAL",
    "CREATE_SUPPORT_TICKET", "CREATE_WORKFORCE_JOB", "QUARANTINE_DEVICE",
)

SENSITIVE_PARAMETER_CATEGORIES = (
    "PPPOE_PASSWORD", "WIFI_PASSWORD", "ACS_CREDENTIAL", "CONNECTION_REQUEST_CREDENTIAL",
    "SIP_CREDENTIAL", "REMOTE_ADMIN_PASSWORD", "DEVICE_ADMIN_PASSWORD", "OTHER_SECRET",
)

# ---------------------------------------------------------------------------
# GenieACS task semantics
# ---------------------------------------------------------------------------
GENIEACS_TASK_STATES = (
    "CREATED", "QUEUED", "CONNECTION_REQUEST_ATTEMPTED", "SESSION_STARTED",
    "RPC_DISPATCHED", "DEVICE_RESPONSE_RECEIVED", "COMPLETED", "FAULTED",
    "VERIFIED", "VERIFICATION_FAILED",
)
CONNECTION_REQUEST_OUTCOMES = (
    "NOT_REQUESTED", "REQUESTED", "ACCEPTED", "UNREACHABLE", "AUTHENTICATION_FAILED",
    "TIMED_OUT", "UNSUPPORTED", "WAITING_FOR_PERIODIC_INFORM",
)

# ---------------------------------------------------------------------------
# Device actions
# ---------------------------------------------------------------------------
DEVICE_ACTION_TYPES = (
    "REFRESH_PARAMETERS", "REFRESH_OBJECT", "REAPPLY_PROFILE", "REBOOT",
    "FACTORY_RESET", "DOWNLOAD_CONFIGURATION", "UPLOAD_CONFIGURATION",
    "CHANGE_PARAMETER", "ADD_OBJECT", "DELETE_OBJECT", "TRIGGER_DIAGNOSTIC",
    "UPGRADE_FIRMWARE", "ROTATE_CREDENTIALS", "CONNECTION_REQUEST", "CLEAR_FAULT",
)
DEVICE_ACTION_STATES = (
    "REQUESTED", "AUTHORIZATION_REQUIRED", "APPROVED", "QUEUED", "WAITING_FOR_DEVICE",
    "EXECUTING", "VERIFYING", "SUCCEEDED", "FAILED", "TIMED_OUT", "CANCELLED",
    "MANUAL_INTERVENTION_REQUIRED",
)
ELEVATED_ACTIONS = {"FACTORY_RESET", "UPGRADE_FIRMWARE"}

# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------
DIAGNOSTIC_TYPES = (
    "PING", "TRACEROUTE", "DOWNLOAD_DIAGNOSTIC", "UPLOAD_DIAGNOSTIC", "UDP_ECHO",
    "DNS_LOOKUP", "WAN_STATUS", "PPP_STATUS", "INTERFACE_STATS", "ETHERNET_LINK",
    "WIFI_RADIO_STATUS", "CONNECTED_HOSTS", "CHANNEL_UTILIZATION", "SIGNAL_STRENGTH",
    "NOISE", "OPTICAL_RX_TX", "UPTIME", "CPU", "MEMORY", "DEVICE_TEMPERATURE",
    "ERROR_COUNTERS", "DEVICE_LOGS", "SELF_TEST",
)
DIAGNOSTIC_JOB_STATES = (
    "REQUESTED", "VALIDATING", "QUEUED", "WAITING_FOR_DEVICE", "RUNNING",
    "COLLECTING_RESULTS", "SUCCEEDED", "FAILED", "TIMED_OUT", "UNSUPPORTED", "CANCELLED",
)
TERMINAL_DIAGNOSTIC_STATES = {"SUCCEEDED", "FAILED", "TIMED_OUT", "UNSUPPORTED", "CANCELLED"}
DIAGNOSTIC_EVALUATIONS = ("PASS", "WARN", "FAIL", "UNKNOWN")

# ---------------------------------------------------------------------------
# Firmware
# ---------------------------------------------------------------------------
FIRMWARE_APPROVAL_STATES = ("UPLOADED", "VALIDATING", "APPROVED", "REJECTED", "QUARANTINED", "ARCHIVED")
FIRMWARE_FILE_TYPES = ("FIRMWARE", "BOOTLOADER", "CONFIGURATION", "OTHER")
FIRMWARE_SIGNATURE_STATUSES = ("UNSIGNED", "SIGNED_VERIFIED", "SIGNED_UNVERIFIED", "SIGNATURE_UNAVAILABLE")

ROLLOUT_STRATEGIES = (
    "LAB", "INTERNAL_TEST", "CANARY", "PERCENTAGE", "MODEL_COHORT",
    "REGION_COHORT", "TENANT_COHORT", "MAINTENANCE_WINDOW", "MANUAL_STAGE", "EMERGENCY",
)
ROLLOUT_STATES = ("DRAFT", "READY", "RUNNING", "PAUSED", "AUTO_PAUSED", "COMPLETED", "STOPPED", "FAILED")
ROLLOUT_STAGE_STATES = ("PENDING", "RUNNING", "SUCCEEDED", "FAILED", "PAUSED", "SKIPPED", "STOPPED")

FIRMWARE_DEPLOYMENT_STATES = (
    "QUEUED", "CONNECTION_REQUEST_PENDING", "TRANSFERRING", "TRANSFERRED",
    "REBOOTING", "WAITING_FOR_INFORM", "VERIFYING", "SUCCEEDED", "FAILED",
    "ROLLED_BACK", "QUARANTINED", "MANUAL_INTERVENTION_REQUIRED",
)
ROLLBACK_CAPABILITIES = ("DUAL_BANK", "VENDOR_DOWNGRADE", "AUTOMATIC_BOOT_ROLLBACK", "MANUAL_ONLY", "NONE")

# ---------------------------------------------------------------------------
# Inventory lifecycle (device side projection)
# ---------------------------------------------------------------------------
INVENTORY_LIFECYCLE_STATES = (
    "PROCURED", "IN_STOCK", "RESERVED", "ISSUED_TO_TECHNICIAN", "INSTALLED",
    "DISCOVERED_IN_ACS", "CLAIMED", "PROVISIONING", "ACTIVE", "OFFLINE", "FAULTY",
    "REPLACEMENT_PENDING", "RECOVERED", "QUARANTINED", "REFURBISHMENT", "RETIRED", "LOST",
)

# ---------------------------------------------------------------------------
# ACS instances
# ---------------------------------------------------------------------------
ACS_ENVIRONMENTS = ("PRODUCTION", "STAGING", "TEST", "LAB")
ACS_HEALTH_STATES = ("UNKNOWN", "HEALTHY", "DEGRADED", "UNREACHABLE", "UNSUPPORTED_VERSION")

# ---------------------------------------------------------------------------
# Telemetry
# ---------------------------------------------------------------------------
TELEMETRY_SIGNALS = (
    "ONLINE", "OFFLINE", "WAN_DOWN", "PPP_DOWN", "HIGH_REBOOT_FREQUENCY",
    "LOW_MEMORY", "HIGH_CPU", "TEMPERATURE_ISSUE", "OPTICAL_OUT_OF_THRESHOLD",
    "FIRMWARE_NON_COMPLIANCE", "CONFIGURATION_DRIFT", "REPEATED_CWMP_FAULT",
    "FAILED_FIRMWARE_UPGRADE",
)
