"""Platform auth foundation; generated schema is explicit and Alembic-owned."""
from alembic import op
import sqlalchemy as sa
revision = "0001_platform_auth"
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    op.create_table("platform_users", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("tenant_id", sa.Uuid()), sa.Column("username", sa.String(128), nullable=False), sa.Column("username_normalized", sa.String(128), nullable=False, unique=True), sa.Column("email", sa.String(255), unique=True), sa.Column("full_name", sa.String(255)), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("failed_login_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("locked_until", sa.DateTime(timezone=True)), sa.Column("password_changed_at", sa.DateTime(timezone=True)), sa.Column("last_login_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    for name, columns in {"platform_roles":[sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("name",sa.String(64),unique=True,nullable=False),sa.Column("global_role",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)],"platform_permissions":[sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("name",sa.String(128),unique=True,nullable=False)]}.items(): op.create_table(name,*columns)
    op.create_table("platform_user_roles",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("platform_users.id",ondelete="CASCADE"),nullable=False),sa.Column("role_id",sa.Uuid(),sa.ForeignKey("platform_roles.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.Uuid()),sa.UniqueConstraint("user_id","role_id","tenant_id",name="uq_platform_user_role"))
    op.create_table("platform_role_permissions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("role_id",sa.Uuid(),sa.ForeignKey("platform_roles.id",ondelete="CASCADE"),nullable=False),sa.Column("permission_id",sa.Uuid(),sa.ForeignKey("platform_permissions.id",ondelete="CASCADE"),nullable=False),sa.UniqueConstraint("role_id","permission_id",name="uq_platform_role_permission"))
    op.create_table("platform_refresh_tokens",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("user_id",sa.Uuid(),sa.ForeignKey("platform_users.id",ondelete="CASCADE"),nullable=False),sa.Column("token_hash",sa.String(64),unique=True,nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.Column("replaced_by_id",sa.Uuid()))
    op.create_table("platform_security_audit_events",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("user_id",sa.Uuid()),sa.Column("action",sa.String(128),nullable=False),sa.Column("detail",sa.Text(),nullable=False,server_default="{}"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
def downgrade():
    for table in ["platform_security_audit_events","platform_refresh_tokens","platform_role_permissions","platform_user_roles","platform_permissions","platform_roles","platform_users"]: op.drop_table(table)
