# Generated by Django 6.0.6 on 2026-07-28 17:06

import django.db.models.deletion
import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0002_customercodesequence_customer_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('utility_bill', 'Utility Bill'), ('address_proof', 'Address Proof'), ('business_registration', 'Business Registration'), ('other', 'Other')], max_length=32)),
                ('document_number', models.CharField(blank=True, max_length=128)),
                ('file', models.FileField(upload_to=kyc.models.kyc_document_upload_path)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_kyc_documents', to='accounts.adminuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_documents', to='customers.customer')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc_documents', to='accounts.adminuser')),
            ],
        ),
    ]
