# Generated by Django 6.0.6 on 2026-08-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('resellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='resellers.branch'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='resellers.franchise'),
        ),
    ]
