# Generated by Django 6.0.6 on 2026-08-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0002_accountingrecord_deleted_at_activesession_deleted_at'),
        ('network', '0004_alter_nasdevice_nas_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingrecord',
            name='nas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_records', to='network.nasdevice'),
        ),
        migrations.AddField(
            model_name='activesession',
            name='nas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_sessions', to='network.nasdevice'),
        ),
    ]
