"""Milestone 10 — canonical enums for the Intelligence Service."""

# ---- Data contracts / pipelines ----
CONTRACT_STATES = ("ACTIVE", "DRAFT", "DEPRECATED", "SUPERSEDED")
RAW_EVENT_STATES = ("VALID", "QUARANTINED", "DUPLICATE", "LATE")
QUALITY_STATES = ("PASS", "FAIL", "WARN")
PIPELINE_STATES = ("RUNNING", "SUCCEEDED", "FAILED", "CANCELLED")
DATASET_STATES = ("DRAFT", "SNAPSHOTTED", "APPROVED", "ARCHIVED")
PII_CLASSES = ("NONE", "PII", "SENSITIVE", "RESTRICTED")
RETENTION_SCOPES = ("TENANT", "GLOBAL")

# ---- Feature store ----
FEATURE_TYPES = ("FLOAT", "INTEGER", "BOOLEAN", "STRING", "CATEGORICAL", "TIMESTAMP")
FEATURE_AVAILABILITY = ("TRAINING_ONLY", "SERVING_ONLY", "TRAINING_AND_SERVING")
FRESHNESS_STATES = ("FRESH", "STALE", "MISSING")

# ---- MLOps ----
TRAINING_STATES = ("QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED")
MODEL_STATES = ("DRAFT", "EVALUATED", "PENDING_APPROVAL", "APPROVED", "REJECTED",
                "SHADOW", "CANARY", "PRODUCTION", "ROLLED_BACK", "RETIRED", "ARCHIVED")
DEPLOYMENT_ENVIRONMENTS = ("SHADOW", "CANARY", "PRODUCTION")
MODEL_SCOPES = ("GLOBAL_BASELINE", "ANONYMIZED_SHARED", "SEGMENT", "TENANT")
DRIFT_TYPES = ("FEATURE", "PREDICTION", "CONCEPT", "CALIBRATION", "DATA_COMPLETENESS")
EVALUATION_METRICS = ("PRECISION", "RECALL", "PR_AUC", "ROC_AUC", "FPR", "FNR",
                      "CALIBRATION", "STABILITY", "BUSINESS_VALUE", "BASELINE_LIFT")

# ---- AIOps use cases ----
AIOPS_USE_CASES = ("FRAUD", "CHURN", "MAINTENANCE", "CAPACITY", "OPTIMIZATION",
                   "RECOMMENDATION", "REMEDIATION")
FRAUD_SEVERITIES = ("LOW", "MEDIUM", "HIGH", "CRITICAL")
FRAUD_STATES = ("OPEN", "IN_REVIEW", "APPROVED", "REJECTED", "CLOSED", "ACTIONED")
FRAUD_DECISIONS = ("NO_ACTION", "MONITOR", "REVIEW", "ESCALATE", "ACTION_RECOMMENDED")
CHURN_HORIZONS = (30, 60, 90)
CHURN_RISK_BANDS = ("LOW", "MEDIUM", "HIGH", "CRITICAL")
RISK_STATES = ("ACTIVE", "EXPIRED", "ACTIONED")
MAINTENANCE_RECOMMENDATIONS = ("INSPECT", "DIAGNOSE", "REPLACE", "CONFIG_VALIDATE", "FIRMWARE_REVIEW")

# ---- Autonomy & remediation ----
AUTONOMY_LEVELS = {"L0": 0, "L1": 1, "L2": 2, "L3": 3, "L4": 4}
REMEDIATION_STATES = ("PENDING", "APPROVED", "REJECTED", "STARTED", "COMPLETED",
                      "FAILED", "COMPENSATED", "CANCELLED", "BLOCKED")
REMEDIATION_STEP_STATES = ("PENDING", "RUNNING", "SUCCEEDED", "FAILED", "SKIPPED", "COMPENSATED")
APPROVAL_DECISIONS = ("APPROVED", "REJECTED")
KILL_SWITCH_SCOPES = ("GLOBAL", "TENANT")
RECOMMENDATION_STATES = ("OPEN", "ACCEPTED", "REJECTED", "EXPIRED", "ACTIONED")
