# Generated by Django 6.0.6 on 2026-08-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
        ('network', '0003_nasdevice_franchise_networklocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdevice',
            name='nas_ip_address',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='nasdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('franchise__isnull', False)), fields=('franchise', 'nas_ip_address'), name='uq_nas_ip_tenant'),
        ),
        migrations.AddConstraint(
            model_name='nasdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('franchise__isnull', True)), fields=('nas_ip_address',), name='uq_nas_ip_legacy'),
        ),
    ]
