"""Canonical enums for the Assurance Service (Milestone 9)."""

# Alert severities
ALERT_SEVERITIES = ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL")

# Alert lifecycle
ALERT_STATES = ("PENDING", "FIRING", "ACKNOWLEDGED", "SUPPRESSED", "SILENCED", "RESOLVED", "EXPIRED")

# Alert definition test status
ALERT_TEST_STATES = ("DRAFT", "VALIDATED", "FAILED")

# Incident lifecycle
INCIDENT_STATES = (
    "DETECTED", "TRIAGE", "INVESTIGATING", "IDENTIFIED", "MITIGATING",
    "MONITORING", "RESOLVED", "CLOSED", "POSTMORTEM_REQUIRED",
)

# Major incident flag handled via is_major boolean.

# Root-cause evidence states
ROOT_CAUSE_STATES = ("OBSERVATION", "HYPOTHESIS", "LIKELY_CAUSE", "CONFIRMED_ROOT_CAUSE", "REJECTED_HYPOTHESIS")

# SLI measurement quality
SLI_QUALITY = ("GOOD", "VALID", "INVALID", "MISSING", "EXCLUDED")

# SLO lifecycle
SLO_STATES = ("DRAFT", "VALIDATING", "APPROVED", "ACTIVE", "SUPERSEDED", "DISABLED", "ARCHIVED")

# SLO window types
SLO_WINDOW_TYPES = ("ROLLING", "CALENDAR")

# Error budget status
ERROR_BUDGET_STATUS = ("HEALTHY", "WARNING", "AT_RISK", "BREACHED", "EXHAUSTED")

# Maintenance window scope
MAINTENANCE_SCOPES = ("TENANT", "SERVICE", "DEVICE", "SITE", "REGION", "PLATFORM")

# Maintenance types
MAINTENANCE_TYPES = ("PLANNED", "EMERGENCY")

# KPI quality
KPI_QUALITY = ("FRESH", "STALE", "INVALID", "EXCLUDED")

# KPI dimension scope
KPI_SCOPES = ("TENANT", "FRANCHISE", "BRANCH", "PLATFORM")

# Synthetic check kinds
SYNTHETIC_KINDS = (
    "LOGIN", "PORTAL_AVAILABILITY", "INVOICE_RETRIEVAL", "PAYMENT_GATEWAY_READINESS",
    "PROVISIONING_API_READINESS", "RADIUS_AUTH", "ROUTEROS_READINESS", "GENIEACS_READINESS",
    "NOTIFICATION_PROVIDER", "OBJECT_STORAGE", "DNS", "TLS_CERTIFICATE",
)

# Synthetic result states
SYNTHETIC_RESULT_STATES = ("PASS", "FAIL", "DEGRADED", "SKIPPED")

# Service criticality
SERVICE_CRITICALITY = ("CRITICAL", "HIGH", "MEDIUM", "LOW")

# Service tiers
SERVICE_TIERS = ("PLATINUM", "GOLD", "SILVER", "STANDARD")

# Telemetry signal kinds (ingested)
TELEMETRY_SIGNALS = ("METRIC", "LOG", "TRACE", "DOMAIN_EVENT", "NETWORK_EVENT", "ALERT", "INCIDENT")

# Network observation kinds
NETWORK_OBSERVATION_KINDS = (
    "ROUTER_REACHABILITY", "INTERFACE_STATE", "INTERFACE_UTILIZATION", "ERRORS_DISCARDS",
    "PACKET_LOSS", "LATENCY", "JITTER", "CPU", "MEMORY", "TEMPERATURE", "BGP_STATE",
    "PPPOE_SESSIONS", "HOTSPOT_SESSIONS", "RADIUS_LATENCY", "AUTH_SUCCESS",
    "ACCOUNTING_FRESHNESS", "POP_HEALTH", "OLT_HEALTH", "PON_PORT", "ONT_HEALTH",
    "OPTICAL_LEVELS", "CPE_INFORM_FRESHNESS", "FIRMWARE_COMPLIANCE", "POLICY_DRIFT",
)

# Impact kinds
IMPACT_KINDS = ("TENANT", "SERVICE", "REGION", "POP", "NAS", "ROUTER", "OLT", "PON_PORT",
                "VLAN", "IP_POOL", "CPE_MODEL", "FIRMWARE_COHORT", "SUBSCRIPTION",
                "ACTIVE_SESSION", "WORKFLOW", "PAYMENT_GATEWAY", "APPLICATION_DEPENDENCY")

# Correlation evidence types
CORRELATION_EVIDENCE_TYPES = ("TIME_PROXIMITY", "TOPOLOGY_DEPENDENCY", "SERVICE_DEPENDENCY",
                              "SHARED_RESOURCE", "TRACE_CAUSALITY", "CORRELATION_ID",
                              "CHANGE_EVENT", "DEPLOYMENT_EVENT", "CONFIG_CHANGE", "FIRMWARE_ROLLOUT",
                              "NETWORK_ALARM", "TICKET_CLUSTER", "HISTORICAL_RECURRENCE", "RECOVERY_SEQUENCE")

# Alert fingerprint label keys (stable only)
ALERT_FINGERPRINT_LABELS = ("service", "component", "severity", "alert_name", "resource", "tenant")
