# Generated by Django 4.2.5 on 2026-08-14 13:21

import billing.models
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_franchise_reseller_franchise'),
        ('accounts', '0004_merge_20260814_0319'),
        ('billing', '0003_billingaccount_deleted_at_invoice_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=billing.models.invoice_import_upload_to)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='UPLOADED', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_invoice_number', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('SKIP', 'Skip'), ('ERROR', 'Error')], db_index=True, max_length=8)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('processing_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('source_row_number',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='import_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_order_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_system',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('source_invoice_number', ''), _negated=True), fields=('subscriber', 'source_system', 'source_invoice_number'), name='uq_invoice_subscriber_source_number'),
        ),
        migrations.AddField(
            model_name='invoiceimportrow',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='billing.invoiceimportbatch'),
        ),
        migrations.AddField(
            model_name='invoiceimportrow',
            name='target_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceimportbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_imports', to='accounts.adminuser'),
        ),
        migrations.AddField(
            model_name='invoiceimportbatch',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_imports', to='customers.franchise'),
        ),
        migrations.AddConstraint(
            model_name='invoiceimportrow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'source_row_number'), name='uq_invoice_import_batch_row'),
        ),
    ]
