"""Canonical enums for the Tenancy Service (Milestone 8)."""

# Tenant lifecycle
TENANT_LIFECYCLE_STATES = (
    "REQUESTED", "VALIDATING", "PROVISIONING", "ACTIVE", "RESTRICTED",
    "SUSPENDED", "OFFBOARDING", "ARCHIVED", "FAILED",
)

# Provisioning saga steps
PROVISIONING_STATES = (
    "REQUESTED", "VALIDATING", "PROVISIONING_CONTROL_RECORD",
    "PROVISIONING_DATABASE", "RUNNING_MIGRATIONS", "CREATING_STORAGE_NAMESPACE",
    "CREATING_MESSAGING_NAMESPACE", "CONFIGURING_DEFAULTS", "CREATING_ADMIN",
    "VERIFYING", "ACTIVE", "FAILED", "ROLLING_BACK", "MANUAL_INTERVENTION_REQUIRED",
)

# Isolation modes
ISOLATION_MODES = (
    "DATABASE_PER_TENANT", "SCHEMA_PER_TENANT", "SHARED_SCHEMA_WITH_RLS",
    "DEDICATED_DEPLOYMENT",
)

# Tenant database health
TENANT_DATABASE_STATES = ("PENDING", "PROVISIONING", "READY", "DEGRADED", "FAILED", "RETIRED")

# Domain states
DOMAIN_STATES = ("PENDING", "VERIFIED", "ACTIVE", "FAILED", "REMOVED")

# Feature flag evaluation
FEATURE_STATES = ("DRAFT", "SCHEDULED", "ENABLED", "DISABLED", "RETIRED")

# Partner types
PARTNER_TYPES = (
    "FRANCHISE", "RESELLER", "DISTRIBUTOR", "MANAGED_OPERATOR",
    "COLLECTION_PARTNER", "FIELD_SERVICE_PARTNER", "NETWORK_PARTNER", "OTHER",
)

# Partner lifecycle
PARTNER_LIFECYCLE_STATES = (
    "PROSPECT", "ONBOARDING", "ACTIVE", "RESTRICTED", "SUSPENDED",
    "TERMINATING", "TERMINATED", "ARCHIVED",
)

# Organization unit types
ORG_UNIT_TYPES = ("TENANT", "LEGAL_ENTITY", "FRANCHISE", "BRANCH", "TEAM", "CENTRAL")

# Ownership roles (customer/service ownership)
OWNERSHIP_ROLES = (
    "ACQUISITION", "SERVICING", "BILLING", "SUPPORT", "NETWORK", "COLLECTION",
)

# RBAC scope kinds
SCOPE_KINDS = (
    "OWN", "ASSIGNED_CUSTOMERS", "BRANCH", "FRANCHISE", "DESCENDANT_ORG_UNITS",
    "TENANT", "PLATFORM_AGGREGATE",
)

# Membership states
MEMBERSHIP_STATES = ("PENDING", "ACTIVE", "SUSPENDED", "REVOKED", "EXPIRED")

# Service account / API credential
CREDENTIAL_STATES = ("ACTIVE", "EXPIRED", "REVOKED", "ROTATING")

# Approval (maker-checker)
APPROVAL_STATES = ("PENDING", "APPROVED", "REJECTED", "CANCELLED")

# Impersonation
IMPERSONATION_STATES = ("REQUESTED", "ACTIVE", "EXPIRED", "REVOKED")

# Commission bases
COMMISSION_BASES = (
    "CUSTOMER_ACQUISITION", "SERVICE_ACTIVATION", "INVOICE_AMOUNT",
    "COLLECTED_REVENUE", "RECURRING_SUBSCRIPTION", "ADD_ON_SALE",
    "USAGE_REVENUE", "INSTALLATION_FEE", "RENEWAL", "PAYMENT_COLLECTION",
    "PRODUCT_SALE", "TERRITORY_PERFORMANCE",
)

# Commission calculation types
COMMISSION_CALCULATION_TYPES = (
    "FIXED_AMOUNT", "PERCENTAGE", "TIERED_PERCENTAGE", "SLAB", "PER_UNIT_AMOUNT",
    "RECURRING_AMOUNT", "ONE_TIME_BONUS", "THRESHOLD_BONUS", "REVENUE_SPLIT",
    "CONDITIONAL_MULTIPLIER",
)

# Earning status
EARNING_STATES = ("RECOGNIZED", "CLAWED_BACK", "ADJUSTED", "SETTLED")

# Adjustment/clawback kinds
FINANCIAL_ADJUSTMENT_KINDS = (
    "CUSTOMER_CANCELLATION", "REFUND", "CHARGEBACK", "PAYMENT_REVERSAL",
    "SERVICE_DEACTIVATION", "FRAUD", "INCORRECT_OWNERSHIP", "MANUAL_CORRECTION",
    "AGREEMENT_CORRECTION",
)

# Settlement lifecycle
SETTLEMENT_STATES = (
    "DRAFT", "CALCULATING", "CALCULATED", "UNDER_REVIEW", "APPROVED", "LOCKED",
    "PAYOUT_PENDING", "PARTIALLY_PAID", "PAID", "RECONCILING", "RECONCILED",
    "DISPUTED", "REVERSED", "CANCELLED",
)

# Settlement line states
SETTLEMENT_LINE_STATES = ("OPEN", "DISPUTED", "PAID", "REVERSED")

# Dispute states
DISPUTE_STATES = ("OPEN", "UNDER_REVIEW", "RESOLVED", "REJECTED", "ESCALATED")

# Wallet entry types
WALLET_ENTRY_TYPES = (
    "OPENING_BALANCE", "DEPOSIT", "CREDIT", "DEBIT", "COMMISSION_EARNING",
    "SETTLEMENT", "ADJUSTMENT", "REFUND", "HOLD", "RELEASE", "TRANSFER",
)

# Report scopes
REPORT_SCOPES = (
    "ORG_UNIT", "FRANCHISE", "BRANCH", "TENANT", "PLATFORM_AGGREGATE", "SHARED_SERVICE",
)

# Reporting entity metrics
REPORT_METRICS = (
    "CUSTOMERS", "LEADS", "ACTIVATIONS", "ACTIVE_SUBSCRIBERS", "CHURN",
    "REVENUE", "COLLECTIONS", "OUTSTANDING", "COMMISSION", "SETTLEMENT",
    "SUPPORT_SLA", "WORKFORCE_SLA", "NETWORK_HEALTH", "DEVICE_HEALTH",
    "PROVISIONING_SUCCESS", "PAYMENT_SUCCESS",
)

# Quota kinds
QUOTA_KINDS = (
    "USERS", "CUSTOMERS", "SUBSCRIBERS", "NAS_DEVICES", "CPE_DEVICES",
    "STORAGE_BYTES", "API_REQUESTS", "REPORTS", "EXPORTS", "RABBITMQ_THROUGHPUT",
    "BACKGROUND_JOBS", "NOTIFICATION_VOLUME", "FIRMWARE_ROLLOUT_SIZE",
)
