# Generated by Django 6.0.6 on 2026-08-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='franchises',
            field=models.ManyToManyField(blank=True, related_name='admin_users', to='customers.franchise'),
        ),
    ]
