# Generated by Django 4.2.5 on 2026-08-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminuser_franchises'),
        ('accounts', '0003_seed_default_admin'),
    ]

    operations = [
    ]
