"""BSS revenue domain enums and state machine constants (Milestone 4)."""
from __future__ import annotations

CURRENCIES = ("INR", "USD", "EUR", "GBP")

PAYMENT_INTENT_STATES = (
    "CREATED",
    "PENDING",
    "REQUIRES_ACTION",
    "PROCESSING",
    "PARTIALLY_PAID",
    "PAID",
    "FAILED",
    "EXPIRED",
    "CANCELLED",
)

PAYMENT_ATTEMPT_STATES = (
    "CREATED",
    "SUBMITTED",
    "AUTHORIZED",
    "CAPTURE_PENDING",
    "CAPTURED",
    "FAILED",
    "CANCELLED",
    "EXPIRED",
    "REFUND_PENDING",
    "PARTIALLY_REFUNDED",
    "REFUNDED",
    "DISPUTED",
    "CHARGEBACK",
)

INVOICE_STATES = (
    "DRAFT",
    "ISSUED",
    "PARTIALLY_PAID",
    "PAID",
    "OVERDUE",
    "VOID",
    "WRITTEN_OFF",
)

MANUAL_PAYMENT_STATES = (
    "DRAFT",
    "SUBMITTED",
    "UNDER_REVIEW",
    "APPROVED",
    "REJECTED",
    "POSTED",
    "REVERSED",
)

RECONCILIATION_STATES = (
    "UNMATCHED",
    "MATCHED",
    "PARTIALLY_MATCHED",
    "MISMATCH",
    "EXCEPTION",
    "MANUAL_REVIEW",
    "RESOLVED",
)

RECONCILIATION_KINDS = ("TRANSACTION", "SETTLEMENT")

JOURNAL_ENTRY_TYPES = ("PAYMENT_CAPTURE", "PAYMENT_REFUND", "CHARGEBACK", "SETTLEMENT", "REVERSAL", "ADJUSTMENT", "CREDIT_NOTE", "DEBIT_NOTE", "MANUAL_PAYMENT", "WRITE_OFF")

GATEWAY_CODES = ("RAZORPAY",)

GATEWAY_METHODS = ("CARD", "UPI", "NETBANKING", "WALLET", "PAYMENT_LINK", "QR", "EMI", "MANDATE")

DUNNING_STAGE_CODES = (
    "UPCOMING_DUE_REMINDER",
    "DUE_DATE_REMINDER",
    "GRACE_PERIOD",
    "FIRST_OVERDUE_REMINDER",
    "ESCALATED_REMINDER",
    "RESTRICTED_SERVICE_WARNING",
    "SUSPENSION_SCHEDULED",
    "SUSPENSION_REQUESTED",
    "SUSPENDED",
    "COLLECTION_REVIEW",
    "TERMINATION_REVIEW",
)

DUNNING_ACTION_TYPES = ("NOTIFY", "SUSPEND", "RESTRICT", "HOLD", "ESCALATE")

DISPUTE_STATUS = ("OPEN", "UNDER_REVIEW", "EVIDENCE_SUBMITTED", "WON", "LOST", "CLOSED")

HOLD_KINDS = ("COLLECTION", "DISPUTE", "LEGAL", "VIP", "VULNERABLE", "ADMINISTRATIVE")

# Reconciliation match rule codes (deterministic priority order).
MATCH_RULES = (
    "EXACT_EXTERNAL_ID",
    "GATEWAY_ORDER_PLUS_AMOUNT",
    "UTR_PLUS_AMOUNT",
    "INVOICE_REFERENCE_PLUS_AMOUNT_DATE",
    "ACCOUNT_REFERENCE_PLUS_AMOUNT_DATE",
    "MANUAL_REVIEW",
)
