# Generated by Django 6.0.6 on 2026-08-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
        ('network', '0002_nasdevice_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasdevice',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nas_devices', to='customers.franchise'),
        ),
        migrations.CreateModel(
            name='NetworkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('node', 'Node'), ('pop', 'POP'), ('switch', 'Switch')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_locations', to='customers.franchise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('franchise', 'kind', 'normalized_name'), name='uq_network_location_scope')],
            },
        ),
    ]
