# Generated by Django 6.0.6 on 2026-08-12 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    NasDevice = apps.get_model("network", "NasDevice")
    for device in NasDevice.objects.filter(public_id__isnull=True).iterator():
        device.public_id = uuid.uuid4()
        device.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminuser_franchises'),
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
        ('network', '0004_alter_nasdevice_nas_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasdevice',
            name='api_port',
            field=models.PositiveIntegerField(default=8729),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='api_protocol',
            field=models.CharField(choices=[('API', 'RouterOS API'), ('API_SSL', 'RouterOS API SSL')], default='API_SSL', max_length=16),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='api_username',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='architecture',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='board_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='ca_certificate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='cached_health',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='certificate_fingerprint',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='coa_port',
            field=models.PositiveIntegerField(default=3799),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='connection_timeout',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nas_devices', to='accounts.adminuser'),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='discovered_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='encrypted_api_password',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='last_connection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='last_error_message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='lifecycle_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TESTING', 'Testing'), ('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Error'), ('DISABLED', 'Disabled')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='nas_type',
            field=models.CharField(default='mikrotik', max_length=64),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='radius_accounting_port',
            field=models.PositiveIntegerField(default=1813),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='radius_auth_port',
            field=models.PositiveIntegerField(default=1812),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='radius_secret_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='radius_source_ip',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='routeros_version',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='selected_radius_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='short_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='system_identity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nas_devices', to='accounts.adminuser'),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='verify_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='nasdevice',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='NasAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=16)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('safe_request_data', models.JSONField(blank=True, default=dict)),
                ('previous_configuration', models.JSONField(blank=True, default=dict)),
                ('new_configuration', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nas_audit_logs', to='customers.franchise')),
                ('nas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='network.nasdevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nas_audit_logs', to='accounts.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='FreeRadiusClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=64)),
                ('nas_type', models.CharField(default='mikrotik', max_length=64)),
                ('secret_encrypted', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freeradius_clients', to='customers.franchise')),
                ('nas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freeradius_client', to='network.nasdevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('franchise', 'source_ip'), name='uq_radius_client_source_tenant')],
            },
        ),
    ]
