# Generated by Django 6.0.6 on 2026-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminuser_franchises'),
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
        ('network', '0005_nasdevice_api_port_nasdevice_api_protocol_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='freeradiusclient',
            name='uq_radius_client_source_tenant',
        ),
        migrations.AlterField(
            model_name='freeradiusclient',
            name='source_ip',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='nasdevice',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('radius_source_ip', ''), _negated=True), ('deleted_at__isnull', True)), fields=('radius_source_ip',), name='uq_nas_radius_source_global'),
        ),
    ]
