# Generated by Django 6.0.6 on 2026-07-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.CharField(max_length=128)),
                ('branch', models.CharField(max_length=128)),
                ('area', models.CharField(blank=True, max_length=128)),
                ('colony', models.CharField(blank=True, max_length=128)),
                ('connection_type', models.CharField(blank=True, choices=[('stu', 'STU'), ('mtu', 'MTU')], max_length=8)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=32)),
                ('alt_mobile', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('lead_source', models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('cold_call', 'Cold Call'), ('social_media', 'Social Media'), ('field_survey', 'Field Survey'), ('other', 'Other')], max_length=32)),
                ('lead_type', models.CharField(choices=[('home', 'Home'), ('business', 'Business')], default='home', max_length=16)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('confirm_fsb_pending', 'Confirm FSB Pending'), ('caf_pending', 'CAF Pending'), ('nc_pending', 'NC Pending'), ('active_closed', 'Active & Closed'), ('not_interested', 'Not Interested'), ('other_closed', 'Other Closed')], db_index=True, default='open', max_length=24)),
                ('is_callback', models.BooleanField(default=False)),
                ('callback_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='accounts.adminuser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to='accounts.adminuser')),
            ],
        ),
    ]
