# Generated by Django 4.2.5 on 2026-08-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_status'),
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
    ]

    operations = [
    ]
