# Generated by Django 4.2.5 on 2026-08-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resellers', '0001_initial'),
        ('customers', '0004_merge_20260814_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='reseller_franchise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_tenant', to='resellers.franchise'),
        ),
    ]
