# Generated by Django 6.0.6 on 2026-08-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
        ('plans', '0002_plan_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='customers.franchise'),
        ),
        migrations.AddField(
            model_name='plan',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='source_sub_package',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
