# Generated by Django 6.0.6 on 2026-08-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_default_admin'),
        ('billing', '0003_billingaccount_deleted_at_invoice_deleted_at_and_more'),
        ('customers', '0003_alter_customer_status'),
        ('plans', '0002_plan_deleted_at'),
        ('resellers', '0001_initial'),
        ('subscribers', '0002_subscriber_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('order_type', models.CharField(choices=[('new_service', 'New Service'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('disconnect', 'Disconnect')], max_length=16)),
                ('subscriber_username', models.CharField(blank=True, max_length=128)),
                ('subscriber_password_hash', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(blank=True, choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot'), ('static_ip', 'Static IP'), ('dhcp', 'DHCP')], max_length=16)),
                ('installation_address', models.CharField(blank=True, max_length=255)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='accounts.adminuser')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='resellers.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='resellers.franchise')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='plans.plan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_orders', to='accounts.adminuser')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='subscribers.subscriber')),
                ('trigger_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_orders', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_changed', 'Status Changed'), ('step_started', 'Step Started'), ('step_completed', 'Step Completed'), ('step_failed', 'Step Failed'), ('step_compensated', 'Step Compensated')], db_index=True, max_length=16)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=16)),
                ('to_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=16)),
                ('step_name', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='orders.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to='accounts.adminuser')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
