"""Explicit NAS orchestration state transitions; callers cannot set states freely."""
LIFECYCLE = {
    "DRAFT": {"CONNECTION_PENDING", "DISABLED", "DECOMMISSIONING"},
    "CONNECTION_PENDING": {"CONNECTION_TESTING", "FAILED", "DISABLED"},
    "CONNECTION_TESTING": {"CONNECTED", "FAILED"},
    "CONNECTED": {"DISCOVERING", "DISABLED"},
    "DISCOVERING": {"DISCOVERED", "FAILED"},
    "DISCOVERED": {"RADIUS_REGISTRATION_PENDING", "CONFIGURATION_PENDING", "DISABLED"},
    "RADIUS_REGISTRATION_PENDING": {"RADIUS_REGISTRATION_CONFIRMED", "FAILED"},
    "RADIUS_REGISTRATION_CONFIRMED": {"CONFIGURATION_PENDING", "DISABLED"},
    "CONFIGURATION_PENDING": {"CONFIGURATION_PLANNED", "FAILED"},
    "CONFIGURATION_PLANNED": {"AWAITING_APPROVAL", "CONFIGURING", "FAILED"},
    "AWAITING_APPROVAL": {"CONFIGURING", "DISABLED"},
    "CONFIGURING": {"VERIFYING", "FAILED"}, "VERIFYING": {"TESTING", "FAILED", "DEGRADED"},
    "TESTING": {"ACTIVE", "DEGRADED", "FAILED"}, "ACTIVE": {"DEGRADED", "DISABLED", "DECOMMISSIONING"},
    "DEGRADED": {"CONFIGURATION_PENDING", "ACTIVE", "DISABLED"}, "FAILED": {"CONNECTION_PENDING", "DISABLED"},
    "DISABLED": {"CONNECTION_PENDING", "DECOMMISSIONING"}, "DECOMMISSIONING": {"DECOMMISSIONED"}, "DECOMMISSIONED": set(),
}
def transition(current: str, target: str) -> str:
    if target not in LIFECYCLE.get(current, set()): raise ValueError(f"invalid NAS lifecycle transition: {current} -> {target}")
    return target
