# Generated by Django 6.0.6 on 2026-08-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('resellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='resellers.branch'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='resellers.franchise'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('billing_admin', 'Billing Admin'), ('noc_admin', 'NOC Admin'), ('support_admin', 'Support Admin'), ('franchise_admin', 'Franchise Admin'), ('branch_admin', 'Branch Admin')], default='super_admin', max_length=32),
        ),
    ]
