# Generated by Django 6.0.6 on 2026-08-12 20:29

import django.db.models.deletion
import subscribers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
        ('network', '0003_nasdevice_franchise_networklocation'),
        ('plans', '0003_plan_franchise_plan_source_name_and_more'),
        ('subscribers', '0002_subscriber_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=subscribers.models.subscriber_import_upload_to)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='UPLOADED', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField()),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('SKIP', 'Skip'), ('ERROR', 'Error')], db_index=True, max_length=8)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('processing_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('source_row_number',),
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='account_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='additional_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='allowed_macs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='connection_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='customers.franchise'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='fup_limit',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='import_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_logoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_payment_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_renewal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='nas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='network.nasdevice'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='nas_port_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_subscribers', to='network.networklocation'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='outage_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='package_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='pop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_subscribers', to='network.networklocation'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='pop_collection_executive',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='pop_technical_executive',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source_package_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source_sub_package',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source_system',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='special_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_subscribers', to='network.networklocation'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='username',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('franchise__isnull', False)), fields=('franchise', 'username'), name='uq_subscriber_username_tenant'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('franchise__isnull', True)), fields=('username',), name='uq_subscriber_username_legacy'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('franchise', 'source_system', 'external_id'), name='uq_subscriber_source_external_tenant'),
        ),
        migrations.AddField(
            model_name='subscriberimportbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriber_imports', to='accounts.adminuser'),
        ),
        migrations.AddField(
            model_name='subscriberimportbatch',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriber_imports', to='customers.franchise'),
        ),
        migrations.AddField(
            model_name='subscriberimportrow',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='subscribers.subscriberimportbatch'),
        ),
        migrations.AddField(
            model_name='subscriberimportrow',
            name='target_subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='subscribers.subscriber'),
        ),
        migrations.AddConstraint(
            model_name='subscriberimportrow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'source_row_number'), name='uq_import_batch_row'),
        ),
    ]
