# Generated by Django 6.0.6 on 2026-08-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_area_branch_customer_address_proof_available_and_more'),
        ('network', '0004_alter_nasdevice_nas_ip_address_and_more'),
        ('plans', '0003_plan_franchise_plan_source_name_and_more'),
        ('subscribers', '0003_subscriberimportbatch_subscriberimportrow_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('mac_address', ''), _negated=True), ('deleted_at__isnull', True), ('franchise__isnull', False)), fields=('franchise', 'mac_address'), name='uq_subscriber_mac_tenant'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('static_ip_address', ''), _negated=True), ('deleted_at__isnull', True), ('franchise__isnull', False)), fields=('franchise', 'static_ip_address'), name='uq_subscriber_ip_tenant'),
        ),
    ]
